### GET request with a header
GET http://localhost:8080
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf =  Xh9HyWSuTZjcvNlxJ9XcNcEJDkBsncOeAlo08hHulEJj0elcZity_FOee_3xirtCEvjoA_ZqI3hcrfCzNWIEwCLapycAstpq

### POST request with json body
GET http://localhost:8080/csrfToken
Content-Type: application/json